from __future__ import annotations

from dataclasses import dataclass


TERMINOLOGY: dict[str, str] = {
    "clean": "翻铃",
    "clean pull": "翻铃拉",
    "hang clean": "悬垂翻铃",
    "half clean": "半蹲翻铃",
    "3-level clean": "三段翻铃",
    "split clean": "箭步翻铃",
    "jump shrug": "跳耸",
    "catch position": "接杠位置",
    "triple extension": "三关节伸展",
    "transition": "转换",
    "progression": "进阶练习",
    "power clean": "力量翻铃",
    "clean and jerk": "挺举",
    "jerk": "上挺",
    "snatch": "抓举",
    "squat": "深蹲",
    "front squat": "前蹲",
    "back squat": "后蹲",
    "pull": "拉",
    "straps": "助力带",
    "weightlifting": "举重",
    "Chinese weightlifting": "中国举重",
    "snatch": "抓举",
    "clean": "翻铃",
    "clean and jerk": "挺举",
    "jerk": "挺举上挺",
    "barbell": "杠铃",
    "start position": "起始姿势",
    "pulling": "提拉",
    "first pull": "第一次提拉",
    "second pull": "第二次提拉",
    "extension": "伸展",
    "catch": "接杠",
    "recovery": "起立恢复",
    "low squat support": "低蹲支撑",
    "jerk dip": "预蹲",
    "jerk drive": "上送",
    "split jerk": "箭步挺",
    "training": "训练",
    "athletic training": "运动训练",
    "preparation": "竞技准备",
    "physical preparation": "身体准备",
    "technical preparation": "技术准备",
    "tactical preparation": "战术准备",
    "mental preparation": "心理准备",
    "intellectual preparation": "知识准备",
    "training content": "训练内容",
    "training means": "训练手段",
    "training methods": "训练方法",
    "training workload": "训练负荷",
    "training volume": "训练量",
    "training intensity": "训练强度",
    "exercise novelty": "练习新颖性",
    "adaptation": "适应",
    "supercompensation": "超量恢复",
    "specificity": "专项性",
    "transfer": "训练迁移",
    "block periodization": "板块周期化",
    "traditional periodization": "传统训练分期模型",
    "delayed training effect": "延迟训练效应",
    "residual training effect": "残留训练效应",
    "trainability": "可训练性",
    "peaking": "竞技状态达峰",
    "technical skills": "技术技能",
    "tactical skills": "战术能力",
    "soccer": "足球",
    "football": "足球",
    "elite soccer": "精英足球",
    "performance coach": "竞技表现教练",
    "strength and conditioning": "体能训练",
    "S&C coach": "体能教练",
    "sport scientist": "运动科学工作人员",
    "performance department": "竞技表现部门",
    "medical department": "医疗部门",
    "academy": "青训学院",
    "youth development": "青训发展",
    "return to play": "重返赛场",
    "return-to-play": "重返赛场",
    "rehabilitation": "康复",
    "end-stage rehab": "末期康复",
    "monitoring": "监控",
    "workload": "训练负荷",
    "external load": "外部负荷",
    "internal load": "内部负荷",
    "periodisation": "周期化安排",
    "periodization": "周期化安排",
    "readiness": "准备状态",
    "availability": "可用性",
    "high-speed running": "高速跑",
    "sprint": "冲刺跑",
    "acceleration": "加速",
    "deceleration": "减速",
    "change of direction": "变向",
    "aerobic capacity": "有氧能力",
    "anaerobic capacity": "无氧能力",
    "hamstring": "腘绳肌",
    "groin": "腹股沟",
    "nutrition": "营养",
    "coaching": "执教",
    "coach": "教练员",
    "athlete development": "运动员发展",
    "program success": "项目成功",
    "core values": "核心价值观",
    "team culture": "团队文化",
    "practice design": "训练课设计",
    "game day": "比赛日",
    "precompetition readiness": "赛前准备状态",
    "postcompetition evaluation": "赛后评估",
    "deliberate practice": "刻意练习",
    "targeted feedback": "针对性反馈",
    "growth mindset": "成长型思维",
    "mastery goals": "掌握性目标",
    "autonomy-supportive coaching": "自主支持型执教",
    "long-term athlete development": "长期运动员发展",
}


@dataclass(frozen=True)
class TerminologyEntry:
    source: str
    target: str


def glossary_lines() -> list[str]:
    return [f"- {source}: {target}" for source, target in sorted(TERMINOLOGY.items())]


def enforce_terms(text: str) -> str:
    replacements = {
        "半程翻铃": "半蹲翻铃",
        "三级翻铃": "三段翻铃",
        "翻铃上拉": "翻铃拉",
        "接铃": "接杠",
        "力量翻站": "力量翻铃",
        "悬挂翻铃": "悬垂翻铃",
        "经典运动训练分期理论": "传统训练分期模型",
        "经典分期理论": "传统训练分期模型",
        "传统周期化理论": "传统训练分期模型",
        "板块训练模式": "板块周期化",
        "非传统板块周期化": "板块周期化",
        "板块分期训练": "板块周期化",
        "超量补偿": "超量恢复",
        "训练痕迹效应": "残留训练效应",
        "剩余训练效应": "残留训练效应",
        "即时训练效应": "急性训练效应",
        "认知性技术技能": "技术技能",
        "认知性专项战术": "战术能力",
        "认知性竞技战术": "战术能力",
        "战术技能": "战术能力",
        "知识准备": "智力准备",
        "特殊原则": "专项性原则",
        "深思熟虑练习": "刻意练习",
        "有意练习": "刻意练习",
        "有针对性的反馈": "针对性反馈",
        "比赛当天": "比赛日",
        "运动员长期发展": "长期运动员发展",
        "长期运动员培养": "长期运动员发展",
        "生长型思维": "成长型思维",
        "自主支持性执教": "自主支持型执教",
        "自主支持式执教": "自主支持型执教",
        "掌握目标": "掌握性目标",
        "团队凝聚性": "团队凝聚力",
    }
    for old, new in replacements.items():
        text = text.replace(old, new)
    return text
